[package]
name = "chip-8"
version = "0.1.0"
authors = ["Robin Le Bihan <robin.le-bihan@epita.fr>"]
edition = "2018"

[dependencies]
clap = "*"
rustyline = "*"
termion = "*"
rand = "0.7"
minifb = "0.13.0"
regex = "1"
